# Tensors
A tensor is essentially a matrix that can have multiple discrete dimensions. For example, a 2D tensor can represent a grayscale or black and white image. Similarly, a 3D tensor can represent a multi-channel color image. Lastly, a 4D tensor can represent a sequence of images.

Among many of the features that PyTorch tensors provide, some important ones are as follows:
- Efficient computation on both CPU and GPU
- Automatic differentiation
- Efficient data I/O

In [50]:
import numpy as np
import pandas as pd
import torch

In [3]:
# Check PyTorch Version
torch.__version__

'1.11.0'

# Initializing Tensor

Tensors can run both in CPU and GPU. `torch.cuda.is_available()` is a convenient function to check if your environment supports GPU.

In [22]:
# setting device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


A `Tensor` can be created from a Python list, with a designated data type, and on a specified device. The `requires_grad` tells whether to compute gradients for any operation with this variable. We will explore this autograd functionality later in this tutorial.

In [23]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float64, device=device, requires_grad=True)
x

tensor([1., 2., 3., 4., 5.], dtype=torch.float64, requires_grad=True)

Each instances of a `Tensor` object has the following usefult properties.

In [56]:
print(x.numel())
print(x.dtype)
print(x.shape)
print(x.ndim)
print(x.requires_grad)
print(x.device)

2
torch.int64
torch.Size([2])
1
False
cpu


`torch.tensor()` always copies data. If you have a numpy array and want to avoid copying, use `torch.as_tensor()`. Finally, remember that the elements in the list that will be converted to tensor must have the same type.

In [24]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
z = torch.as_tensor(y)
z

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The values of y is not copied to z. rather they are using the ame memory address. So, any change in z will be reflected in y.

In [26]:
print(id(y))
print(id(z))

140645431909616
140645448602544


We can also use the `from_numpy` function to convert a `ndarray` into a `tensor`. However, this function copies the element of the `ndarray` to create a new `tensor`.

In [40]:
z = torch.from_numpy(y)
z

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

As evident below, both `y` and `z` have different memory addresses.

In [42]:
print(id(y))
print(id(z))

140645431909616
140645688563728


We can also convert a `tensor` back to a `ndarray` using the `numpy()` function.

In [43]:
z.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can also create a `tensor` from a `Pandas` `Series` data structure. We can simply convert a `Series` into a `ndarray` using the `values` property. Then we can simply use the `as_tensor` or `from_numpy` function to create a new `tensor`.

In [53]:
series = pd.Series([1, 2, 3, 4, 5, 6],
                    index=['January', 'February', 'March', 'April', 'May', 'June'])
series

January     1
February    2
March       3
April       4
May         5
June        6
dtype: int64

In [54]:
torch.as_tensor(series.values)

tensor([1, 2, 3, 4, 5, 6])

There are several useful shorthands for quickly creating tensors of arbitrary shapes.

In [46]:
x = torch.empty((3, 3))
y = torch.zeros((2, 2))
z = torch.ones((3, 3))
p = torch.rand((2, 2))
q = torch.eye(5, 5)

In [47]:
print(x)

tensor([[0.0000, 1.8750, 0.0000],
        [2.0000, 0.0000, 2.1250],
        [0.0000, 2.2500, 0.0000]])


Further methods for creating `tensor`s. A useful function for plotting mathematical functions is <code>torch.linspace()</code>. <code>torch.linspace()</code> returns evenly spaced numbers over a specified interval. You specify the starting point of the sequence and the ending point of the sequence. The parameter <code>steps</code> indicates the number of samples to generate.

In [48]:
x = torch.arange(start=10, end=20, step=5)
y = torch.linspace(start=10, end=20, steps=5)

In [49]:
print(y)

tensor([10.0000, 12.5000, 15.0000, 17.5000, 20.0000])


Finally, we can use `tolist` function to convert a `tensor` directly to a `Python` list.

In [55]:
y.tolist()

[10.0, 12.5, 15.0, 17.5, 20.0]

# Type Casting

In [57]:
x = torch.arange(4)
print(x)
print(x.dtype)

tensor([0, 1, 2, 3])
torch.int64


In [58]:
# convert to boolean
print(x.bool())
# convert to int16
print(x.short())
# convert to int64
print(x.long())
# convert to float16
print(x.half())
# convert to float32
print(x.float())
# convert to float64
print(x.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


# Math Operations

In [50]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [51]:
# addition
z = x + y
print(z)
# subtraction
z = x - y
print(z)
# element-wise division
z = x / y
print(z)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])


In [52]:
# inplace operations, more efficient
x.add_(y)
print(x)
x.subtract_(y)
print(x)
x.pow_(2)
print(x)

tensor([5, 7, 9])
tensor([1, 2, 3])
tensor([1, 4, 9])


In [55]:
# matrix multiplication
x = torch.rand((4, 2))
y = torch.rand((2, 5))
x.mm(y)

tensor([[0.6538, 0.2213, 0.3961, 0.2471, 0.3605],
        [0.6991, 0.8080, 0.6728, 0.3265, 0.9714],
        [1.0976, 0.9709, 0.9264, 0.4801, 1.2198],
        [0.1213, 0.2460, 0.1629, 0.0682, 0.2771]])

In [61]:
# batch matrix multiplication
batch = 64
x = torch.rand((batch, 10, 20))
y = torch.rand((batch, 20, 30))
x.bmm(y).shape

torch.Size([64, 10, 30])

In [58]:
# element-wise multiplication
x = torch.arange(5)
y = torch.arange(5, 10)
x * y

tensor([ 0,  6, 14, 24, 36])

In [59]:
# dot product
x.dot(y)

tensor(80)

In [86]:
x = torch.rand((5))
y = torch.rand((5))
print(x)
print(y)

tensor([0.7044, 0.5909, 0.8720, 0.7822, 0.6886])
tensor([0.3628, 0.5099, 0.6645, 0.3284, 0.1134])


In [87]:
print(x < y)
print(x > y)
print(x == y)
print(x != y)

tensor([False, False, False, False, False])
tensor([True, True, True, True, True])
tensor([False, False, False, False, False])
tensor([True, True, True, True, True])


# Broadcasting

In [62]:
x = torch.rand((5, 5))
y = torch.rand((1, 5))
print(x.shape)
print(y.shape)

torch.Size([5, 5])
torch.Size([1, 5])


In [64]:
# (1, 5) vector is broadcasted to each row of (5, 5) matrix
x + y

tensor([[0.6004, 1.3465, 1.0038, 0.7690, 1.1236],
        [0.8425, 1.2952, 1.1865, 0.9104, 0.6444],
        [0.7170, 0.9198, 0.6625, 0.2941, 0.8117],
        [0.9239, 0.5734, 1.2844, 0.7062, 0.6146],
        [1.0561, 1.3646, 0.5560, 0.2834, 0.8981]])

# Useful Functions

In [75]:
x = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [76]:
# row-wise sum
print(x.sum(dim=0))
# column-wise sum
print(x.sum(dim=1))

tensor([ 7,  9, 11, 13, 15])
tensor([15, 40])


In [78]:
# returns the minimum element of each column
print(x.min(dim=0))
# returns the minimum element of each row
print(x.min(dim=1))

torch.return_types.min(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 0, 0, 0, 0]))
torch.return_types.min(
values=tensor([1, 6]),
indices=tensor([0, 0]))


In [79]:
# returns the maximum element of each row
print(x.max(dim=1))
# returns the maximum element of each column
print(x.max(dim=0))

torch.return_types.max(
values=tensor([ 5, 10]),
indices=tensor([4, 4]))
torch.return_types.max(
values=tensor([ 6,  7,  8,  9, 10]),
indices=tensor([1, 1, 1, 1, 1]))


In [80]:
# returns the position of the maximum element row-wise
print(x.argmax(dim=1))
# returns the position of the maximum element column-wise
print(x.argmax(dim=0))

tensor([4, 4])
tensor([1, 1, 1, 1, 1])


In [82]:
# returns the position of the minimum element row-wise
print(x.argmin(dim=1))
# returns the position of the minimum element column-wise
print(x.argmin(dim=0))

tensor([0, 0])
tensor([0, 0, 0, 0, 0])


In [85]:
# returns means of each column
print(torch.mean(x.float(), dim=0))

tensor([3.5000, 4.5000, 5.5000, 6.5000, 7.5000])


In [91]:
# sorts tensor
x = torch.rand(10)
print(x)
x, indices = x.sort(descending=False)
print(x)
print(indices)

tensor([0.9291, 0.8346, 0.5642, 0.6347, 0.0324, 0.5313, 0.6205, 0.4015, 0.3922,
        0.4558])
tensor([0.0324, 0.3922, 0.4015, 0.4558, 0.5313, 0.5642, 0.6205, 0.6347, 0.8346,
        0.9291])
tensor([4, 8, 7, 9, 5, 2, 6, 3, 1, 0])


In [92]:
# clamp tensor between values
x = torch.tensor([0, 1, 4, 5, 6, 7, 10, 11])
print(x)
# any element less than 2 is set to 2, and any element more than 10 is set to 10
x = x.clamp(min=2, max=10)
print(x)

tensor([ 0,  1,  4,  5,  6,  7, 10, 11])
tensor([ 2,  2,  4,  5,  6,  7, 10, 10])


In [93]:
x = torch.tensor([0, 0, 1, 1, 1], dtype=torch.bool)
# checks if any of the values is true
print(x.any())
# checks if all the values are true
print(x.all())

tensor(True)
tensor(False)


# Indexing
The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation.

In [59]:
batch_size = 64
feature_size = (3, 256, 256)

img = torch.rand((batch_size, *feature_size))

In [60]:
# selecting first image
print(img[0].shape)
# selecting first color channel of first image
print(img[0, 0].shape)
# selecting first row of first color channel of first image
print(img[0, 0, 0].shape)
# slecting first column of first color channel of first image
print(img[0, 0, :, 0].shape)

torch.Size([3, 256, 256])
torch.Size([256, 256])
torch.Size([256])
torch.Size([256])


The number on the left side of the colon represents the index of the first value. The number on the right side of the colon is always 1 larger than the index of the last value. For example, <code>tensor_sample\[1:4]</code> means you get values from the index 1 to index 3 <i>(4-1)</i>.

In [61]:
# selecting 3rd column of 2nd color channel of all images
print(img[:, 1, :, 2].shape)
# selecting 3rd column of 2nd color channel of first 10 images
print(img[:10, 1, :, 2].shape)

torch.Size([64, 256])
torch.Size([10, 256])


We can leverage `Fancy Indexing` and use boolean conditions to select specific values too.

In [62]:
x = torch.tensor([1, 2, 3, 4, 5])
print(x < 4)
print(x[x < 4])
print((x < 2) | (x > 4))
print(x[(x < 2) | (x > 4)])
print((x < 3) & (x < 2))
print(x[(x < 3) & (x < 2)])

tensor([ True,  True,  True, False, False])
tensor([1, 2, 3])
tensor([ True, False, False, False,  True])
tensor([1, 5])
tensor([ True, False, False, False, False])
tensor([1])


The `where` function returns elements as it is if condition is met, otherwise changes value according to given formulae.

In [66]:
x.where(x < 2, x + 100)

tensor([  1, 102, 103, 104, 105])

The `unique` function returns the unique elements in the list.

In [68]:
x.unique()

tensor([1, 2, 3, 4, 5])

Use `torch.Tensor.item()` to get a Python number from a tensor containing a single value.

In [69]:
# Returns a single item
x[0].item()

1

If we can select a specific value or a range of values from a `tensor`, we can also assign new values to those positions. For example, below we have selected the first 2 items of `x` and assigned new values to them.

In [73]:
print(x)

tensor([100, 101,   3,   4,   5])


In [74]:
x[0:2] = torch.tensor([100, 101])
x

tensor([100, 101,   3,   4,   5])

# Reshaping

In [28]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
print(x.shape)
print(x.ndim)

torch.Size([12])
1


The`view` function can be used to reshape a vector. For example, before `x` was a 1 dimensional vector. Later we reshaped it into a 2 dimensional matrix with 3 rows and 4 columns. The number of elements in a tensor must remain constant after applying view.

In [33]:
x_reshaped = x.view(3, 4)
x_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [34]:
print(x_reshaped.shape)
print(x_reshaped.ndim)

torch.Size([3, 4])
2


 However, `view` requires contiguous memory, in contrast to `reshape`. Therefore, `reshape` is safe to use in expanse of performance.

In [35]:
print(x.reshape(3, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


If you have a tensor with dynamic size, you can use `-1` to represent any size. But you can set only one dimension as `-1`.

In [36]:
x.view(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [131]:
# concatenates two tensors
x = torch.rand((3, 3))
y = torch.rand((3, 3))

In [132]:
# concatenates x and y column-wise
print(torch.cat((x, y), dim=0))

tensor([[0.5758, 0.8272, 0.5018],
        [0.8797, 0.4139, 0.5342],
        [0.2559, 0.6678, 0.5250],
        [0.9736, 0.8642, 0.6723],
        [0.0595, 0.5665, 0.6810],
        [0.6280, 0.3432, 0.9762]])


In [134]:
# concatenates x and y row-wise
print(torch.cat((x, y), dim=1))

tensor([[0.5758, 0.8272, 0.5018, 0.9736, 0.8642, 0.6723],
        [0.8797, 0.4139, 0.5342, 0.0595, 0.5665, 0.6810],
        [0.2559, 0.6678, 0.5250, 0.6280, 0.3432, 0.9762]])


In [135]:
# unrolling all elements
x.reshape(-1)

tensor([0.5758, 0.8272, 0.5018, 0.8797, 0.4139, 0.5342, 0.2559, 0.6678, 0.5250])

In [138]:
print(img.shape)
# converting 2d color images into a vector of pixels
print(img.reshape(64, -1).shape)

torch.Size([64, 3, 256, 256])
torch.Size([64, 196608])


In [140]:
# swapping dimensions, changing colour channel dimension to the last
print(img.permute(0, 2, 3, 1).shape)

torch.Size([64, 256, 256, 3])


In [153]:
# add and remove a single dimension to the existing one
x = torch.arange(10)
print(x)
x = x.unsqueeze(0)
print(x.shape)
print(x.unsqueeze(2).shape)
print(x.squeeze(0).shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 10])
torch.Size([1, 10, 1])
torch.Size([10])


# Autograd
A tensor can be created with `requires_grad=True` so that `torch.autograd` records operations on them for automatic differentiation. For example, we know that
$$y = x^2$$
$$\frac{\mathrm{dy(x)}}{\mathrm{dx}}=2x$$
$$\frac{\mathrm{dy(x=2)}}{\mathrm{dx}}=2(2)=4$$


In [94]:
x = torch.tensor([2], dtype=torch.float32, requires_grad=True)
x

tensor([2.], requires_grad=True)

In [95]:
y = x ** 2
y

tensor([4.], grad_fn=<PowBackward0>)

In [96]:
y.backward()
print("The dervative at x = 2: ", x.grad)

The dervative at x = 2:  tensor([4.])
